[0m09:36:45.237432 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C8DA9AB00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C90B7EF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C90B7D600>]}


============================== 09:36:45.246024 | a1a48be7-e642-4710-99fa-ce39c93dcf86 ==============================
[0m09:36:45.246024 [info ] [MainThread]: Running with dbt=1.7.1
[0m09:36:45.247024 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\SAP\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:36:55.413052 [debug] [MainThread]: Starter project path: C:\Saulo\GitHub\notebook-python\dbt_apagar\dbt_venv\lib\site-packages\dbt\include\starter_project
[0m09:36:55.476031 [info ] [MainThread]: 
Your new dbt project "dbt_apagar" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:36:55.477463 [info ] [MainThread]: Setting up your profile.
[0m09:37:34.751400 [info ] [MainThread]: Profile dbt_apagar written to C:\Users\SAP\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m09:37:34.757686 [debug] [MainThread]: Command `dbt init` succeeded at 09:37:34.757686 after 49.58 seconds
[0m09:37:34.758230 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C8DA9AB00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C90B7EF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C90B2F700>]}
[0m09:37:34.759294 [debug] [MainThread]: Flushing usage events
[0m09:37:47.228364 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFE5F9B2E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFE917E5F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFE917D660>]}


============================== 09:37:47.228364 | ec5f71cf-a655-4c88-b72e-2d573b060654 ==============================
[0m09:37:47.228364 [info ] [MainThread]: Running with dbt=1.7.1
[0m09:37:47.228364 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\SAP\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:37:47.228364 [info ] [MainThread]: dbt version: 1.7.1
[0m09:37:47.228364 [info ] [MainThread]: python version: 3.10.11
[0m09:37:47.228364 [info ] [MainThread]: python path: C:\Saulo\GitHub\notebook-python\dbt_apagar\dbt_venv\Scripts\python.exe
[0m09:37:47.228364 [info ] [MainThread]: os info: Windows-10-10.0.22621-SP0
[0m09:37:47.594346 [info ] [MainThread]: Using profiles dir at C:\Users\SAP\.dbt
[0m09:37:47.595305 [info ] [MainThread]: Using profiles.yml file at C:\Users\SAP\.dbt\profiles.yml
[0m09:37:47.596319 [info ] [MainThread]: Using dbt_project.yml file at C:\Saulo\GitHub\notebook-python\dbt_apagar\dbt_project.yml
[0m09:37:47.597427 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:37:47.598434 [debug] [MainThread]: Command `dbt debug` failed at 09:37:47.598434 after 0.43 seconds
[0m09:37:47.599473 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFE5F9B2E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFE912B5B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFE9A67490>]}
[0m09:37:47.600020 [debug] [MainThread]: Flushing usage events
[0m09:38:35.617431 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F37389B820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F376982E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F3769801C0>]}


============================== 09:38:35.622570 | 908b283f-63da-426b-b866-289544c0b1f2 ==============================
[0m09:38:35.622570 [info ] [MainThread]: Running with dbt=1.7.1
[0m09:38:35.623040 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\SAP\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:38:35.624053 [info ] [MainThread]: dbt version: 1.7.1
[0m09:38:35.624599 [info ] [MainThread]: python version: 3.10.11
[0m09:38:35.624599 [info ] [MainThread]: python path: C:\Saulo\GitHub\notebook-python\dbt_apagar\dbt_venv\Scripts\python.exe
[0m09:38:35.625871 [info ] [MainThread]: os info: Windows-10-10.0.22621-SP0
[0m09:38:35.974977 [info ] [MainThread]: Using profiles dir at C:\Users\SAP\.dbt
[0m09:38:35.990611 [info ] [MainThread]: Using profiles.yml file at C:\Users\SAP\.dbt\profiles.yml
[0m09:38:35.991541 [info ] [MainThread]: Using dbt_project.yml file at C:\Saulo\GitHub\Notebook-Python\dbt_apagar\dbt_project.yml
[0m09:38:35.991541 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:38:35.994466 [debug] [MainThread]: Command `dbt debug` failed at 09:38:35.991541 after 0.43 seconds
[0m09:38:35.994466 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F37389B820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F37692F550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F37729A740>]}
[0m09:38:35.994466 [debug] [MainThread]: Flushing usage events
[0m09:39:10.920303 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DBF39AB00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DC257EF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DC257D600>]}


============================== 09:39:10.924315 | ad3dfdcd-8860-4eca-b84f-eff979efa1d1 ==============================
[0m09:39:10.924315 [info ] [MainThread]: Running with dbt=1.7.1
[0m09:39:10.925312 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\SAP\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:39:10.926311 [info ] [MainThread]: dbt version: 1.7.1
[0m09:39:10.927311 [info ] [MainThread]: python version: 3.10.11
[0m09:39:10.927311 [info ] [MainThread]: python path: C:\Saulo\GitHub\notebook-python\dbt_apagar\dbt_venv\Scripts\python.exe
[0m09:39:10.928310 [info ] [MainThread]: os info: Windows-10-10.0.22621-SP0
[0m09:39:11.292206 [info ] [MainThread]: Using profiles dir at C:\Users\SAP\.dbt
[0m09:39:11.292666 [info ] [MainThread]: Using profiles.yml file at C:\Users\SAP\.dbt\profiles.yml
[0m09:39:11.293784 [info ] [MainThread]: Using dbt_project.yml file at C:\Saulo\GitHub\Notebook-Python\dbt_apagar\dbt_project.yml
[0m09:39:11.295038 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:39:11.296340 [debug] [MainThread]: Command `dbt debug` failed at 09:39:11.296340 after 0.43 seconds
[0m09:39:11.296340 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DBF39AB00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DC2E6C700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DC2E6E8C0>]}
[0m09:39:11.297346 [debug] [MainThread]: Flushing usage events
[0m09:39:31.296401 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216FE2DB820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021681683E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021681680DF0>]}


============================== 09:39:31.300437 | 14312ec6-780e-4d6b-847a-83c651e17205 ==============================
[0m09:39:31.300437 [info ] [MainThread]: Running with dbt=1.7.1
[0m09:39:31.301399 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\SAP\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:39:31.302400 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Saulo\GitHub\Notebook-Python\dbt_apagar\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:39:31.304404 [debug] [MainThread]: Command `dbt run` failed at 09:39:31.303404 after 0.06 seconds
[0m09:39:31.304404 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216FE2DB820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021681681B70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021681681870>]}
[0m09:39:31.305404 [debug] [MainThread]: Flushing usage events
[0m10:59:37.575450 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029902C9B2E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029905E7FE50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029905E7D7B0>]}


============================== 10:59:37.580167 | 96ac27ec-1f4f-4714-b996-c4cdd4001322 ==============================
[0m10:59:37.580167 [info ] [MainThread]: Running with dbt=1.7.1
[0m10:59:37.580167 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\SAP\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt compile', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:59:37.585274 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Saulo\GitHub\Notebook-Python\dbt_apagar\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:59:37.585274 [debug] [MainThread]: Command `dbt compile` failed at 10:59:37.585274 after 0.07 seconds
[0m10:59:37.585274 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029902C9B2E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029905E7DAE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029905E7DD20>]}
[0m10:59:37.585274 [debug] [MainThread]: Flushing usage events
